use_frameworks!

platform :ios, '9.0'

target 'BlobPrivateComponentDemo_Example' do
  pod 'BlobPrivateComponentDemo', :path => '../'

  target 'BlobPrivateComponentDemo_Tests' do
    inherit! :search_paths

    
  end
end
